#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Abp_InteractiveActor

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Abp_InteractiveActor.Abp_InteractiveActor_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct Abp_InteractiveActor_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_Abp_InteractiveActor_C_AnimGraph;

// Function Abp_InteractiveActor.Abp_InteractiveActor_C.ExecuteUbergraph_Abp_InteractiveActor
// 0x0004 (0x0004 - 0x0000)
struct Abp_InteractiveActor_C_ExecuteUbergraph_Abp_InteractiveActor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Abp_InteractiveActor_C_ExecuteUbergraph_Abp_InteractiveActor;

}

