#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_pds_lingzhijing_03a

#include "Basic.hpp"

#include "Abp_HumanoidCS_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_pds_lingzhijing_03a.ABP_pds_lingzhijing_03a_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01C0 - 0x01C0)
struct ABP_pds_lingzhijing_03a::FAnimBlueprintGeneratedConstantData final : public Abp_HumanoidCS::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_ABP_pds_lingzhijing_03a__FAnimBlueprintGeneratedConstantData;

}

