#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_wukong_head_lingzhi

#include "Basic.hpp"

#include "Abp_ModularMeshCS_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_wukong_head_lingzhi.ABP_wukong_head_lingzhi_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0150 - 0x0150)
struct ABP_wukong_head_lingzhi::FAnimBlueprintGeneratedConstantData final : public Abp_ModularMeshCS::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_ABP_wukong_head_lingzhi__FAnimBlueprintGeneratedConstantData;

}

