#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Abp_HumanoidCS_Simple4Dir

#include "Basic.hpp"

#include "Abp_HumanoidCS_Simple4Dir_classes.hpp"
#include "Abp_HumanoidCS_Simple4Dir_parameters.hpp"


namespace SDK
{

// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbp_HumanoidCS_Simple4Dir_C::ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir");

	Params::Abp_HumanoidCS_Simple4Dir_C_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_F9B8D6D242AEAA75FB435F80A681A584
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_F9B8D6D242AEAA75FB435F80A681A584()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_F9B8D6D242AEAA75FB435F80A681A584");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_D102B5B8414212C266469CAD833AACB3
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_D102B5B8414212C266469CAD833AACB3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_D102B5B8414212C266469CAD833AACB3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_BBCC167249B3F206916C6D8749070E0B
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_BBCC167249B3F206916C6D8749070E0B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_BBCC167249B3F206916C6D8749070E0B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_9B82B7134310A46AA01B3EB1BD58CF18
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_9B82B7134310A46AA01B3EB1BD58CF18()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_9B82B7134310A46AA01B3EB1BD58CF18");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_61B479AA4B4E26AF9E356C9A27DFAF1D
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_61B479AA4B4E26AF9E356C9A27DFAF1D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_61B479AA4B4E26AF9E356C9A27DFAF1D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_35C984434C1F5F898F593BB514E5956C
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_35C984434C1F5F898F593BB514E5956C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_35C984434C1F5F898F593BB514E5956C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_1071C6D745E7C01659E7EF980DA34D64
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_1071C6D745E7C01659E7EF980DA34D64()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_TransitionResult_1071C6D745E7C01659E7EF980DA34D64");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_SequencePlayer_A87E1822407ECB0E657412AAA73B4BA9
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_SequencePlayer_A87E1822407ECB0E657412AAA73B4BA9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_SequencePlayer_A87E1822407ECB0E657412AAA73B4BA9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_D35932C7404D125E33B0F2B6AB9D7E28
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_D35932C7404D125E33B0F2B6AB9D7E28()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_D35932C7404D125E33B0F2B6AB9D7E28");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_71387B3C4302358A8D5D5887DDC22A19
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_71387B3C4302358A8D5D5887DDC22A19()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_71387B3C4302358A8D5D5887DDC22A19");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_2953EC634E9365C1EBA3618085A896D9
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_2953EC634E9365C1EBA3618085A896D9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_2953EC634E9365C1EBA3618085A896D9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1B511D7041E0C6A313D2F98EEEDF6B94
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1B511D7041E0C6A313D2F98EEEDF6B94()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1B511D7041E0C6A313D2F98EEEDF6B94");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1807C5B4455D7B071974BBB76625E78E
// (BlueprintEvent)

void UAbp_HumanoidCS_Simple4Dir_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1807C5B4455D7B071974BBB76625E78E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Abp_HumanoidCS_Simple4Dir_AnimGraphNode_BlendListByBool_1807C5B4455D7B071974BBB76625E78E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Abp_HumanoidCS_Simple4Dir.Abp_HumanoidCS_Simple4Dir_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAbp_HumanoidCS_Simple4Dir_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Abp_HumanoidCS_Simple4Dir_C", "AnimGraph");

	Params::Abp_HumanoidCS_Simple4Dir_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

