#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Abp_ModularMeshCS

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Abp_ModularMeshCS.Abp_ModularMeshCS_C.ExecuteUbergraph_Abp_ModularMeshCS
// 0x0010 (0x0010 - 0x0000)
struct Abp_ModularMeshCS_C_ExecuteUbergraph_Abp_ModularMeshCS final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FTrunc_A_WideningCast;                    // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Abp_ModularMeshCS_C_ExecuteUbergraph_Abp_ModularMeshCS;

// Function Abp_ModularMeshCS.Abp_ModularMeshCS_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct Abp_ModularMeshCS_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_Abp_ModularMeshCS_C_AnimGraph;

}

