#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Abp_box5

#include "Basic.hpp"

#include "Abp_box_base_structs.hpp"


namespace SDK
{

// ScriptStruct Abp_box5.Abp_box5_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0108 - 0x0108)
struct Abp_box5::FAnimBlueprintGeneratedConstantData final : public Abp_box_base::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_Abp_box5__FAnimBlueprintGeneratedConstantData;

}

