#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BI_LockEnemy

#include "Basic.hpp"

#include "BI_LockEnemy_classes.hpp"
#include "BI_LockEnemy_parameters.hpp"


namespace SDK
{

// Function BI_LockEnemy.BI_LockEnemy_C.ChangeLockType
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TargetLockType                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBI_LockEnemy_C::ChangeLockType(int32 TargetLockType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BI_LockEnemy_C", "ChangeLockType");

	Params::BI_LockEnemy_C_ChangeLockType Parms{};

	Parms.TargetLockType = TargetLockType;

	UObject::ProcessEvent(Func, &Parms);
}

}

