#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BI_Loading_BossRushEnemy

#include "Basic.hpp"

#include "b1_Managed_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BI_Loading_BossRushEnemy.BI_Loading_BossRushEnemy_C
// 0x0018 (0x03F0 - 0x03D8)
class UBI_Loading_BossRushEnemy_C final : public UBUI_Widget
{
public:
	class UImage*                                 ImgArrow;                                          // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImgIcon;                                           // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImgSelected;                                       // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BI_Loading_BossRushEnemy_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BI_Loading_BossRushEnemy_C")
	}
	static class UBI_Loading_BossRushEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBI_Loading_BossRushEnemy_C>();
	}
};
DUMPER7_ASSERTS_UBI_Loading_BossRushEnemy_C;

}

