#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BI_TransStyle_24

#include "Basic.hpp"

#include "b1_Managed_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BI_TransStyle_24.BI_TransStyle_24_C
// 0x0008 (0x03E8 - 0x03E0)
class UBI_TransStyle_24_C final : public UBI_TransStyle25CS
{
public:
	class UBI_TransStyleBase_24_C*                BI_TransStyleBase;                                 // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BI_TransStyle_24_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BI_TransStyle_24_C")
	}
	static class UBI_TransStyle_24_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBI_TransStyle_24_C>();
	}
};
DUMPER7_ASSERTS_UBI_TransStyle_24_C;

}

