#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DestructibleBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_FXActorBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DestructibleBase.BP_DestructibleBase_C
// 0x0020 (0x0350 - 0x0330)
class ABP_DestructibleBase_C : public ABP_FXActorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBUS_SceneInactiveActorComp*            BUS_SceneInactiveActorComp;                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   ShowMesh;                                          // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleComponent*                 Destructible;                                      // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void OnHitDestructible_1(const struct FVector& HitLocation, const struct FVector& ImpulseDir, float ImpulseStrength, float Damage);
	void ExecuteUbergraph_BP_DestructibleBase(int32 EntryPoint);
	void BreakMesh(const struct FVector& HitLocation, const struct FVector& ImpulseDir, ECollisionEnabled CollisionEnableTypeAfterHit, double ImpulseStrength);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DestructibleBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DestructibleBase_C")
	}
	static class ABP_DestructibleBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DestructibleBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_DestructibleBase_C;

}

