#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_manualsplinemove_volume

#include "Basic.hpp"

#include "b1_Managed_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_manualsplinemove_volume.BP_manualsplinemove_volume_C
// 0x0000 (0x0318 - 0x0318)
class ABP_manualsplinemove_volume_C final : public ABGUManualSplineMoveVolume
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_manualsplinemove_volume_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_manualsplinemove_volume_C")
	}
	static class ABP_manualsplinemove_volume_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_manualsplinemove_volume_C>();
	}
};
DUMPER7_ASSERTS_ABP_manualsplinemove_volume_C;

}

