#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Player_Wukong_KangJinLong_Lightning

#include "Basic.hpp"

#include "b1_Managed_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Player_Wukong_KangJinLong_Lightning.BP_Player_Wukong_KangJinLong_Lightning_C
// 0x0010 (0x0380 - 0x0370)
class ABP_Player_Wukong_KangJinLong_Lightning_C final : public ABGUBulletBaseManaged
{
public:
	class UCapsuleComponent*                      CheckComp_Capsule;                                 // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NG_Lightning;                                      // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Player_Wukong_KangJinLong_Lightning_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Player_Wukong_KangJinLong_Lightning_C")
	}
	static class ABP_Player_Wukong_KangJinLong_Lightning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Player_Wukong_KangJinLong_Lightning_C>();
	}
};
DUMPER7_ASSERTS_ABP_Player_Wukong_KangJinLong_Lightning_C;

}

