#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BUI_Interact

#include "Basic.hpp"

#include "BUI_Interact_classes.hpp"
#include "BUI_Interact_parameters.hpp"


namespace SDK
{

// Function BUI_Interact.BUI_Interact_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBUI_Interact_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BUI_Interact_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BUI_Interact.BUI_Interact_C.ExecuteUbergraph_BUI_Interact
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBUI_Interact_C::ExecuteUbergraph_BUI_Interact(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BUI_Interact_C", "ExecuteUbergraph_BUI_Interact");

	Params::BUI_Interact_C_ExecuteUbergraph_BUI_Interact Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

