#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BUI_AnimShowBlock

#include "Basic.hpp"

#include "b1_Managed_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BUI_AnimShowBlock.BUI_AnimShowBlock_C
// 0x0008 (0x03E0 - 0x03D8)
class UBUI_AnimShowBlock_C final : public UBUI_Widget
{
public:
	class UButton*                                BG_Button;                                         // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BUI_AnimShowBlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BUI_AnimShowBlock_C")
	}
	static class UBUI_AnimShowBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBUI_AnimShowBlock_C>();
	}
};
DUMPER7_ASSERTS_UBUI_AnimShowBlock_C;

}

