#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BUI_BloodBarList

#include "Basic.hpp"

#include "BUI_BloodBarList_classes.hpp"
#include "BUI_BloodBarList_parameters.hpp"


namespace SDK
{

// Function BUI_BloodBarList.BUI_BloodBarList_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBUI_BloodBarList_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BUI_BloodBarList_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BUI_BloodBarList.BUI_BloodBarList_C.ExecuteUbergraph_BUI_BloodBarList
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBUI_BloodBarList_C::ExecuteUbergraph_BUI_BloodBarList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BUI_BloodBarList_C", "ExecuteUbergraph_BUI_BloodBarList");

	Params::BUI_BloodBarList_C_ExecuteUbergraph_BUI_BloodBarList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BUI_BloodBarList.BUI_BloodBarList_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBUI_BloodBarList_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BUI_BloodBarList_C", "PreConstruct");

	Params::BUI_BloodBarList_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

