#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BUI_BloodBarList

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "b1_Managed_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BUI_BloodBarList.BUI_BloodBarList_C
// 0x0018 (0x03F0 - 0x03D8)
class UBUI_BloodBarList_C final : public UBUI_Widget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       AKBLayoutType;                                     // 0x03E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBI_BloodBarList_C*                     BI_BloodBarList;                                   // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_BUI_BloodBarList(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BUI_BloodBarList_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BUI_BloodBarList_C")
	}
	static class UBUI_BloodBarList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBUI_BloodBarList_C>();
	}
};
DUMPER7_ASSERTS_UBUI_BloodBarList_C;

}

