#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CS_wukong_tttb

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CS_wukong_tttb.CS_wukong_tttb_C
// 0x0000 (0x0230 - 0x0230)
class UCS_wukong_tttb_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CS_wukong_tttb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CS_wukong_tttb_C")
	}
	static class UCS_wukong_tttb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCS_wukong_tttb_C>();
	}
};
DUMPER7_ASSERTS_UCS_wukong_tttb_C;

}

