#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GeometryScriptingCore

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum GeometryScriptingCore.EGeometryScriptCollisionGenerationMethod
// NumValues: 0x0008
enum class EGeometryScriptCollisionGenerationMethod : uint8
{
	AlignedBoxes                             = 0,
	OrientedBoxes                            = 1,
	MinimalSpheres                           = 2,
	Capsules                                 = 3,
	ConvexHulls                              = 4,
	SweptHulls                               = 5,
	MinVolumeShapes                          = 6,
	EGeometryScriptCollisionGenerationMethod_MAX = 7,
};

// Enum GeometryScriptingCore.EGeometryScriptSweptHullAxis
// NumValues: 0x0006
enum class EGeometryScriptSweptHullAxis : uint8
{
	X                                        = 0,
	Y                                        = 1,
	Z                                        = 2,
	SmallestBoxDimension                     = 3,
	SmallestVolume                           = 4,
	EGeometryScriptSweptHullAxis_MAX         = 5,
};

// Enum GeometryScriptingCore.EGeometryScriptOutcomePins
// NumValues: 0x0003
enum class EGeometryScriptOutcomePins : uint8
{
	Failure                                  = 0,
	Success                                  = 1,
	EGeometryScriptOutcomePins_MAX           = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptSearchOutcomePins
// NumValues: 0x0003
enum class EGeometryScriptSearchOutcomePins : uint8
{
	Found                                    = 0,
	NotFound                                 = 1,
	EGeometryScriptSearchOutcomePins_MAX     = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptContainmentOutcomePins
// NumValues: 0x0003
enum class EGeometryScriptContainmentOutcomePins : uint8
{
	Inside                                   = 0,
	Outside                                  = 1,
	EGeometryScriptContainmentOutcomePins_MAX = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptLODType
// NumValues: 0x0005
enum class EGeometryScriptLODType : uint8
{
	MaxAvailable                             = 0,
	HiResSourceModel                         = 1,
	SourceModel                              = 2,
	RenderData                               = 3,
	EGeometryScriptLODType_MAX               = 4,
};

// Enum GeometryScriptingCore.EGeometryScriptIndexType
// NumValues: 0x0006
enum class EGeometryScriptIndexType : uint8
{
	Any                                      = 0,
	Triangle                                 = 1,
	Vertex                                   = 2,
	MaterialID                               = 3,
	PolygroupID                              = 4,
	EGeometryScriptIndexType_MAX             = 5,
};

// Enum GeometryScriptingCore.EGeometryScriptDebugMessageType
// NumValues: 0x0003
enum class EGeometryScriptDebugMessageType : uint8
{
	ErrorMessage                             = 0,
	WarningMessage                           = 1,
	EGeometryScriptDebugMessageType_MAX      = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptErrorType
// NumValues: 0x0005
enum class EGeometryScriptErrorType : uint8
{
	NoError                                  = 0,
	UnknownError                             = 1,
	InvalidInputs                            = 2,
	OperationFailed                          = 3,
	EGeometryScriptErrorType_MAX             = 4,
};

// Enum GeometryScriptingCore.EGeometryScriptBooleanOperation
// NumValues: 0x0004
enum class EGeometryScriptBooleanOperation : uint8
{
	Union                                    = 0,
	Intersection                             = 1,
	Subtract                                 = 2,
	EGeometryScriptBooleanOperation_MAX      = 3,
};

// Enum GeometryScriptingCore.EGeometryScriptFlareType
// NumValues: 0x0004
enum class EGeometryScriptFlareType : uint8
{
	SinMode                                  = 0,
	SinSquaredMode                           = 1,
	TriangleMode                             = 2,
	EGeometryScriptFlareType_MAX             = 3,
};

// Enum GeometryScriptingCore.EGeometryScriptMathWarpType
// NumValues: 0x0004
enum class EGeometryScriptMathWarpType : uint8
{
	SinWave1D                                = 0,
	SinWave2D                                = 1,
	SinWave3D                                = 2,
	EGeometryScriptMathWarpType_MAX          = 3,
};

// Enum GeometryScriptingCore.EGeometryScriptTangentTypes
// NumValues: 0x0003
enum class EGeometryScriptTangentTypes : uint8
{
	FastMikkT                                = 0,
	PerTriangle                              = 1,
	EGeometryScriptTangentTypes_MAX          = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptPrimitivePolygroupMode
// NumValues: 0x0004
enum class EGeometryScriptPrimitivePolygroupMode : uint8
{
	SingleGroup                              = 0,
	PerFace                                  = 1,
	PerQuad                                  = 2,
	EGeometryScriptPrimitivePolygroupMode_MAX = 3,
};

// Enum GeometryScriptingCore.EGeometryScriptPrimitiveOriginMode
// NumValues: 0x0003
enum class EGeometryScriptPrimitiveOriginMode : uint8
{
	Center                                   = 0,
	Base                                     = 1,
	EGeometryScriptPrimitiveOriginMode_MAX   = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptPrimitiveUVMode
// NumValues: 0x0003
enum class EGeometryScriptPrimitiveUVMode : uint8
{
	Uniform                                  = 0,
	ScaleToFill                              = 1,
	EGeometryScriptPrimitiveUVMode_MAX       = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptFillHolesMethod
// NumValues: 0x0006
enum class EGeometryScriptFillHolesMethod : uint8
{
	Automatic                                = 0,
	MinimalFill                              = 1,
	PolygonTriangulation                     = 2,
	TriangleFan                              = 3,
	PlanarProjection                         = 4,
	EGeometryScriptFillHolesMethod_MAX       = 5,
};

// Enum GeometryScriptingCore.EGeometryScriptRemoveHiddenTrianglesMethod
// NumValues: 0x0003
enum class EGeometryScriptRemoveHiddenTrianglesMethod : uint8
{
	FastWindingNumber                        = 0,
	RaycastOcclusionTest                     = 1,
	EGeometryScriptRemoveHiddenTrianglesMethod_MAX = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptRemoveMeshSimplificationType
// NumValues: 0x0004
enum class EGeometryScriptRemoveMeshSimplificationType : uint8
{
	StandardQEM                              = 0,
	VolumePreserving                         = 1,
	AttributeAware                           = 2,
	EGeometryScriptRemoveMeshSimplificationType_MAX = 3,
};

// Enum GeometryScriptingCore.EGeometryScriptUVFlattenMethod
// NumValues: 0x0003
enum class EGeometryScriptUVFlattenMethod : uint8
{
	ExpMap                                   = 0,
	Conformal                                = 1,
	EGeometryScriptUVFlattenMethod_MAX       = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptUVIslandSource
// NumValues: 0x0003
enum class EGeometryScriptUVIslandSource : uint8
{
	PolyGroups                               = 0,
	UVIslands                                = 1,
	EGeometryScriptUVIslandSource_MAX        = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptGridSizingMethod
// NumValues: 0x0003
enum class EGeometryScriptGridSizingMethod : uint8
{
	GridCellSize                             = 0,
	GridResolution                           = 1,
	EGeometryScriptGridSizingMethod_MAX      = 2,
};

// Enum GeometryScriptingCore.EGeometryScriptMorphologicalOpType
// NumValues: 0x0005
enum class EGeometryScriptMorphologicalOpType : uint8
{
	Dilate                                   = 0,
	Contract                                 = 1,
	Close                                    = 2,
	Open                                     = 3,
	EGeometryScriptMorphologicalOpType_MAX   = 4,
};

// ScriptStruct GeometryScriptingCore.GeometryScriptCollisionFromMeshOptions
// 0x0020 (0x0020 - 0x0000)
struct FGeometryScriptCollisionFromMeshOptions final
{
public:
	bool                                          bEmitTransaction;                                  // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGeometryScriptCollisionGenerationMethod      Method;                                            // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoDetectSpheres;                                // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoDetectBoxes;                                  // 0x0003(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAutoDetectCapsules;                               // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MinThickness;                                      // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSimplifyHulls;                                    // 0x000C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ConvexHullTargetFaceCount;                         // 0x0010(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SweptHullSimplifyTolerance;                        // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGeometryScriptSweptHullAxis                  SweptHullAxis;                                     // 0x0018(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRemoveFullyContainedShapes;                       // 0x0019(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxShapeCount;                                     // 0x001C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptCollisionFromMeshOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptSetSimpleCollisionOptions
// 0x0001 (0x0001 - 0x0000)
struct FGeometryScriptSetSimpleCollisionOptions final
{
public:
	bool                                          bEmitTransaction;                                  // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptSetSimpleCollisionOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptConvexHullOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptConvexHullOptions final
{
public:
	bool                                          bPrefilterVertices;                                // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PrefilterGridResolution;                           // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SimplifyToFaceCount;                               // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptConvexHullOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptSweptHullOptions
// 0x0018 (0x0018 - 0x0000)
struct FGeometryScriptSweptHullOptions final
{
public:
	bool                                          bPrefilterVertices;                                // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PrefilterGridResolution;                           // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinThickness;                                      // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSimplify;                                         // 0x000C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MinEdgeLength;                                     // 0x0010(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SimplifyTolerance;                                 // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptSweptHullOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshReadLOD
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptMeshReadLOD final
{
public:
	EGeometryScriptLODType                        LODType;                                           // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LODIndex;                                          // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshReadLOD;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshWriteLOD
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptMeshWriteLOD final
{
public:
	bool                                          bWriteHiResSource;                                 // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LODIndex;                                          // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshWriteLOD;

// ScriptStruct GeometryScriptingCore.GeometryScriptTriangle
// 0x0048 (0x0048 - 0x0000)
struct FGeometryScriptTriangle final
{
public:
	struct FVector                                Vector0;                                           // 0x0000(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Vector1;                                           // 0x0018(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Vector2;                                           // 0x0030(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptTriangle;

// ScriptStruct GeometryScriptingCore.GeometryScriptTrianglePoint
// 0x0038 (0x0038 - 0x0000)
struct FGeometryScriptTrianglePoint final
{
public:
	bool                                          bValid;                                            // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TriangleID;                                        // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                position;                                          // 0x0008(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                BaryCoords;                                        // 0x0020(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptTrianglePoint;

// ScriptStruct GeometryScriptingCore.GeometryScriptUVTriangle
// 0x0030 (0x0030 - 0x0000)
struct FGeometryScriptUVTriangle final
{
public:
	struct FVector2D                              UV0;                                               // 0x0000(0x0010)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              UV1;                                               // 0x0010(0x0010)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              UV2;                                               // 0x0020(0x0010)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptUVTriangle;

// ScriptStruct GeometryScriptingCore.GeometryScriptColorFlags
// 0x0004 (0x0004 - 0x0000)
struct FGeometryScriptColorFlags final
{
public:
	bool                                          bRed;                                              // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bGreen;                                            // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBlue;                                             // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAlpha;                                            // 0x0003(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptColorFlags;

// ScriptStruct GeometryScriptingCore.GeometryScriptGroupLayer
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptGroupLayer final
{
public:
	bool                                          bDefaultLayer;                                     // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ExtendedLayerIndex;                                // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptGroupLayer;

// ScriptStruct GeometryScriptingCore.GeometryScriptIndexList
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FGeometryScriptIndexList final
{
public:
	EGeometryScriptIndexType                      IndexType;                                         // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x17];                                       // 0x0001(0x0017)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptIndexList;

// ScriptStruct GeometryScriptingCore.GeometryScriptTriangleList
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FGeometryScriptTriangleList final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptTriangleList;

// ScriptStruct GeometryScriptingCore.GeometryScriptVectorList
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FGeometryScriptVectorList final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptVectorList;

// ScriptStruct GeometryScriptingCore.GeometryScriptUVList
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FGeometryScriptUVList final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptUVList;

// ScriptStruct GeometryScriptingCore.GeometryScriptColorList
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FGeometryScriptColorList final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptColorList;

// ScriptStruct GeometryScriptingCore.GeometryScriptDynamicMeshBVH
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FGeometryScriptDynamicMeshBVH final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptDynamicMeshBVH;

// ScriptStruct GeometryScriptingCore.GeometryScriptDebugMessage
// 0x0020 (0x0020 - 0x0000)
struct FGeometryScriptDebugMessage final
{
public:
	EGeometryScriptDebugMessageType               MessageType;                                       // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGeometryScriptErrorType                      ErrorType;                                         // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Message;                                           // 0x0008(0x0018)(BlueprintVisible, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptDebugMessage;

// ScriptStruct GeometryScriptingCore.GeometryScriptCopyMeshFromAssetOptions
// 0x0003 (0x0003 - 0x0000)
struct FGeometryScriptCopyMeshFromAssetOptions final
{
public:
	bool                                          bApplyBuildSettings;                               // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRequestTangents;                                  // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIgnoreRemoveDegenerates;                          // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptCopyMeshFromAssetOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptNaniteOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptNaniteOptions final
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FallbackPercentTriangles;                          // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FallbackRelativeError;                             // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptNaniteOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptCopyMeshToAssetOptions
// 0x0040 (0x0040 - 0x0000)
struct FGeometryScriptCopyMeshToAssetOptions final
{
public:
	bool                                          bEnableRecomputeNormals;                           // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableRecomputeTangents;                          // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableRemoveDegenerates;                          // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bReplaceMaterials;                                 // 0x0003(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInterface*>             NewMaterials;                                      // 0x0008(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<class FName>                           NewMaterialSlotNames;                              // 0x0018(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          bApplyNaniteSettings;                              // 0x0028(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometryScriptNaniteOptions           NaniteSettings;                                    // 0x002C(0x000C)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bEmitTransaction;                                  // 0x0038(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bDeferMeshPostEditChange;                          // 0x0039(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptCopyMeshToAssetOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptSimpleMeshBuffers
// 0x00D0 (0x00D0 - 0x0000)
struct FGeometryScriptSimpleMeshBuffers final
{
public:
	TArray<struct FVector>                        Vertices;                                          // 0x0000(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        Normals;                                           // 0x0010(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV0;                                               // 0x0020(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV1;                                               // 0x0030(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV2;                                               // 0x0040(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV3;                                               // 0x0050(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV4;                                               // 0x0060(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV5;                                               // 0x0070(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV6;                                               // 0x0080(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector2D>                      UV7;                                               // 0x0090(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FLinearColor>                   VertexColors;                                      // 0x00A0(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FIntVector>                     Triangles;                                         // 0x00B0(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 TriGroupIDs;                                       // 0x00C0(0x0010)(BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptSimpleMeshBuffers;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshBooleanOptions
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptMeshBooleanOptions final
{
public:
	bool                                          bFillHoles;                                        // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSimplifyOutput;                                   // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SimplifyPlanarTolerance;                           // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshBooleanOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshSelfUnionOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptMeshSelfUnionOptions final
{
public:
	bool                                          bFillHoles;                                        // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTrimFlaps;                                        // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSimplifyOutput;                                   // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SimplifyPlanarTolerance;                           // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WindingThreshold;                                  // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshSelfUnionOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshPlaneCutOptions
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptMeshPlaneCutOptions final
{
public:
	bool                                          bFillHoles;                                        // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFillSpans;                                        // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFlipCutSide;                                      // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         UVWorldDimension;                                  // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshPlaneCutOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshPlaneSliceOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptMeshPlaneSliceOptions final
{
public:
	bool                                          bFillHoles;                                        // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFillSpans;                                        // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GapWidth;                                          // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         UVWorldDimension;                                  // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshPlaneSliceOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshMirrorOptions
// 0x0003 (0x0003 - 0x0000)
struct FGeometryScriptMeshMirrorOptions final
{
public:
	bool                                          bApplyPlaneCut;                                    // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFlipCutSide;                                      // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bWeldAlongPlane;                                   // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshMirrorOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptIsSameMeshOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptIsSameMeshOptions final
{
public:
	bool                                          bCheckConnectivity;                                // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckEdgeIDs;                                     // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckNormals;                                     // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckColors;                                      // 0x0003(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckUVs;                                         // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckGroups;                                      // 0x0005(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckAttributes;                                  // 0x0006(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Epsilon;                                           // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptIsSameMeshOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeasureMeshDistanceOptions
// 0x0001 (0x0001 - 0x0000)
struct FGeometryScriptMeasureMeshDistanceOptions final
{
public:
	bool                                          bSymmetric;                                        // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeasureMeshDistanceOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptBendWarpOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptBendWarpOptions final
{
public:
	bool                                          bSymmetricExtents;                                 // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LowerExtent;                                       // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBidirectional;                                    // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptBendWarpOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptTwistWarpOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptTwistWarpOptions final
{
public:
	bool                                          bSymmetricExtents;                                 // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LowerExtent;                                       // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bBidirectional;                                    // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptTwistWarpOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptFlareWarpOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptFlareWarpOptions final
{
public:
	bool                                          bSymmetricExtents;                                 // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LowerExtent;                                       // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGeometryScriptFlareType                      FlareType;                                         // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptFlareWarpOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptPerlinNoiseLayerOptions
// 0x0028 (0x0028 - 0x0000)
struct FGeometryScriptPerlinNoiseLayerOptions final
{
public:
	float                                         Magnitude;                                         // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Frequency;                                         // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                FrequencyShift;                                    // 0x0008(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RandomSeed;                                        // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptPerlinNoiseLayerOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMathWarpOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptMathWarpOptions final
{
public:
	float                                         Magnitude;                                         // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Frequency;                                         // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FrequencyShift;                                    // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMathWarpOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptPerlinNoiseOptions
// 0x0030 (0x0030 - 0x0000)
struct FGeometryScriptPerlinNoiseOptions final
{
public:
	struct FGeometryScriptPerlinNoiseLayerOptions BaseLayer;                                         // 0x0000(0x0028)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bApplyAlongNormal;                                 // 0x0028(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptPerlinNoiseOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptIterativeMeshSmoothingOptions
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptIterativeMeshSmoothingOptions final
{
public:
	int32                                         NumIterations;                                     // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         alpha;                                             // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptIterativeMeshSmoothingOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptDisplaceFromTextureOptions
// 0x0030 (0x0030 - 0x0000)
struct FGeometryScriptDisplaceFromTextureOptions final
{
public:
	float                                         Magnitude;                                         // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              UVScale;                                           // 0x0008(0x0010)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              UVOffset;                                          // 0x0018(0x0010)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Center;                                            // 0x0028(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ImageChannel;                                      // 0x002C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptDisplaceFromTextureOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshOffsetOptions
// 0x0018 (0x0018 - 0x0000)
struct FGeometryScriptMeshOffsetOptions final
{
public:
	float                                         OffsetDistance;                                    // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFixedBoundary;                                    // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SolveSteps;                                        // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SmoothAlpha;                                       // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bReprojectDuringSmoothing;                         // 0x0010(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BoundaryAlpha;                                     // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMeshOffsetOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshExtrudeOptions
// 0x0028 (0x0028 - 0x0000)
struct FGeometryScriptMeshExtrudeOptions final
{
public:
	float                                         ExtrudeDistance;                                   // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                ExtrudeDirection;                                  // 0x0008(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         UVScale;                                           // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSolidsToShells;                                   // 0x0024(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptMeshExtrudeOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMeshBevelOptions
// 0x00C0 (0x00C0 - 0x0000)
struct FGeometryScriptMeshBevelOptions final
{
public:
	float                                         BevelDistance;                                     // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInferMaterialID;                                  // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SetMaterialID;                                     // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bApplyFilterBox;                                   // 0x000C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBox                                   FilterBox;                                         // 0x0010(0x0038)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x8];                                       // 0x0048(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             FilterBoxTransform;                                // 0x0050(0x0060)(BlueprintVisible, IsPlainOldData, NoDestructor, AdvancedDisplay, NativeAccessSpecifierPublic)
	bool                                          bFullyContained;                                   // 0x00B0(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B1[0xF];                                       // 0x00B1(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptMeshBevelOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptCalculateNormalsOptions
// 0x0002 (0x0002 - 0x0000)
struct FGeometryScriptCalculateNormalsOptions final
{
public:
	bool                                          bAngleWeighted;                                    // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAreaWeighted;                                     // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptCalculateNormalsOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptSplitNormalsOptions
// 0x0014 (0x0014 - 0x0000)
struct FGeometryScriptSplitNormalsOptions final
{
public:
	bool                                          bSplitByOpeningAngle;                              // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         OpeningAngleDeg;                                   // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSplitByFaceGroup;                                 // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometryScriptGroupLayer              GroupLayer;                                        // 0x000C(0x0008)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptSplitNormalsOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptTangentsOptions
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptTangentsOptions final
{
public:
	EGeometryScriptTangentTypes                   Type;                                              // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         UVLayer;                                           // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptTangentsOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptPrimitiveOptions
// 0x0003 (0x0003 - 0x0000)
struct FGeometryScriptPrimitiveOptions final
{
public:
	EGeometryScriptPrimitivePolygroupMode         PolygroupMode;                                     // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFlipOrientation;                                  // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGeometryScriptPrimitiveUVMode                UVMode;                                            // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptPrimitiveOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptRevolveOptions
// 0x0014 (0x0014 - 0x0000)
struct FGeometryScriptRevolveOptions final
{
public:
	float                                         RevolveDegrees;                                    // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DegreeOffset;                                      // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bReverseDirection;                                 // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHardNormals;                                      // 0x0009(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HardNormalAngle;                                   // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bProfileAtMidpoint;                                // 0x0010(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFillPartialRevolveEndcaps;                        // 0x0011(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptRevolveOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptWeldEdgesOptions
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptWeldEdgesOptions final
{
public:
	float                                         Tolerance;                                         // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOnlyUniquePairs;                                  // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptWeldEdgesOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptFillHolesOptions
// 0x0002 (0x0002 - 0x0000)
struct FGeometryScriptFillHolesOptions final
{
public:
	EGeometryScriptFillHolesMethod                FillMethod;                                        // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x1];                                        // 0x0001(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptFillHolesOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptRemoveSmallComponentOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptRemoveSmallComponentOptions final
{
public:
	float                                         MinVolume;                                         // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinArea;                                           // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MinTriangleCount;                                  // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptRemoveSmallComponentOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptRemoveHiddenTrianglesOptions
// 0x001C (0x001C - 0x0000)
struct FGeometryScriptRemoveHiddenTrianglesOptions final
{
public:
	EGeometryScriptRemoveHiddenTrianglesMethod    Method;                                            // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SamplesPerTriangle;                                // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ShrinkSelection;                                   // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WindingIsoValue;                                   // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RaysPerSample;                                     // 0x0010(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NormalOffset;                                      // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCompactResult;                                    // 0x0018(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptRemoveHiddenTrianglesOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptPlanarSimplifyOptions
// 0x0004 (0x0004 - 0x0000)
struct FGeometryScriptPlanarSimplifyOptions final
{
public:
	float                                         AngleThreshold;                                    // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptPlanarSimplifyOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptPolygroupSimplifyOptions
// 0x0004 (0x0004 - 0x0000)
struct FGeometryScriptPolygroupSimplifyOptions final
{
public:
	float                                         AngleThreshold;                                    // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptPolygroupSimplifyOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptSimplifyMeshOptions
// 0x0006 (0x0006 - 0x0000)
struct FGeometryScriptSimplifyMeshOptions final
{
public:
	EGeometryScriptRemoveMeshSimplificationType   Method;                                            // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAllowSeamCollapse;                                // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAllowSeamSmoothing;                               // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAllowSeamSplits;                                  // 0x0003(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bPreserveVertexPositions;                          // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRetainQuadricMemory;                              // 0x0005(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptSimplifyMeshOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptSpatialQueryOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptSpatialQueryOptions final
{
public:
	float                                         MaxDistance;                                       // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAllowUnsafeModifiedQueries;                       // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         WindingIsoThreshold;                               // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptSpatialQueryOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptRayHitResult
// 0x0040 (0x0040 - 0x0000)
struct FGeometryScriptRayHitResult final
{
public:
	bool                                          bHit;                                              // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RayParameter;                                      // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HitTriangleID;                                     // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                HitPosition;                                       // 0x0010(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                HitBaryCoords;                                     // 0x0028(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptRayHitResult;

// ScriptStruct GeometryScriptingCore.GeometryScriptPNTessellateOptions
// 0x0001 (0x0001 - 0x0000)
struct FGeometryScriptPNTessellateOptions final
{
public:
	bool                                          bRecomputeNormals;                                 // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptPNTessellateOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptRepackUVsOptions
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptRepackUVsOptions final
{
public:
	int32                                         TargetImageWidth;                                  // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOptimizeIslandRotation;                           // 0x0004(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptRepackUVsOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptExpMapUVOptions
// 0x0008 (0x0008 - 0x0000)
struct FGeometryScriptExpMapUVOptions final
{
public:
	int32                                         NormalSmoothingRounds;                             // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NormalSmoothingAlpha;                              // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptExpMapUVOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptRecomputeUVsOptions
// 0x0018 (0x0018 - 0x0000)
struct FGeometryScriptRecomputeUVsOptions final
{
public:
	EGeometryScriptUVFlattenMethod                Method;                                            // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGeometryScriptUVIslandSource                 IslandSource;                                      // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometryScriptExpMapUVOptions         ExpMapOptions;                                     // 0x0004(0x0008)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	struct FGeometryScriptGroupLayer              GroupLayer;                                        // 0x000C(0x0008)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bAutoAlignIslandsWithAxes;                         // 0x0014(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGeometryScriptRecomputeUVsOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptPatchBuilderOptions
// 0x0034 (0x0034 - 0x0000)
struct FGeometryScriptPatchBuilderOptions final
{
public:
	int32                                         InitialPatchCount;                                 // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MinPatchSize;                                      // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PatchCurvatureAlignmentWeight;                     // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PatchMergingMetricThresh;                          // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PatchMergingAngleThresh;                           // 0x0010(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGeometryScriptExpMapUVOptions         ExpMapOptions;                                     // 0x0014(0x0008)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bRespectInputGroups;                               // 0x001C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometryScriptGroupLayer              GroupLayer;                                        // 0x0020(0x0008)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bAutoPack;                                         // 0x0028(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometryScriptRepackUVsOptions        PackingOptions;                                    // 0x002C(0x0008)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptPatchBuilderOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptXAtlasOptions
// 0x0004 (0x0004 - 0x0000)
struct FGeometryScriptXAtlasOptions final
{
public:
	int32                                         MaxIterations;                                     // 0x0000(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptXAtlasOptions;

// ScriptStruct GeometryScriptingCore.GeometryScript3DGridParameters
// 0x000C (0x000C - 0x0000)
struct FGeometryScript3DGridParameters final
{
public:
	EGeometryScriptGridSizingMethod               SizeMethod;                                        // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GridCellSize;                                      // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GridResolution;                                    // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScript3DGridParameters;

// ScriptStruct GeometryScriptingCore.GeometryScriptSolidifyOptions
// 0x001C (0x001C - 0x0000)
struct FGeometryScriptSolidifyOptions final
{
public:
	struct FGeometryScript3DGridParameters        GridParameters;                                    // 0x0000(0x000C)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	float                                         WindingThreshold;                                  // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSolidAtBoundaries;                                // 0x0010(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ExtendBounds;                                      // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SurfaceSearchSteps;                                // 0x0018(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptSolidifyOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptMorphologyOptions
// 0x0024 (0x0024 - 0x0000)
struct FGeometryScriptMorphologyOptions final
{
public:
	struct FGeometryScript3DGridParameters        SDFGridParameters;                                 // 0x0000(0x000C)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bUseSeparateMeshGrid;                              // 0x000C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometryScript3DGridParameters        MeshGridParameters;                                // 0x0010(0x000C)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	EGeometryScriptMorphologicalOpType            Operation;                                         // 0x001C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Distance;                                          // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptMorphologyOptions;

// ScriptStruct GeometryScriptingCore.GeometryScriptCopyMeshFromComponentOptions
// 0x000C (0x000C - 0x0000)
struct FGeometryScriptCopyMeshFromComponentOptions final
{
public:
	bool                                          bWantNormals;                                      // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bWantTangents;                                     // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometryScriptMeshReadLOD             RequestedLOD;                                      // 0x0004(0x0008)(BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FGeometryScriptCopyMeshFromComponentOptions;

}

