#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GSUMGExt

#include "Basic.hpp"


namespace SDK::Params
{

// Function GSUMGExt.GSSearchBox.GetText
// 0x0018 (0x0018 - 0x0000)
struct GSSearchBox_GetText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GSSearchBox_GetText;

// Function GSUMGExt.GSSplitterBoxSlot.SetSize
// 0x0004 (0x0004 - 0x0000)
struct GSSplitterBoxSlot_SetSize final
{
public:
	float                                         InSize;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GSSplitterBoxSlot_SetSize;

// Function GSUMGExt.GSSplitterBox.AddChildToSplitterBox
// 0x0010 (0x0010 - 0x0000)
struct GSSplitterBox_AddChildToSplitterBox final
{
public:
	class UWidget*                                Content;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UGSSplitterBoxSlot*                     ReturnValue;                                       // 0x0008(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GSSplitterBox_AddChildToSplitterBox;

}

