#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hephaestus

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class Hephaestus.HephaestusBPLibrary
// 0x0000 (0x0028 - 0x0028)
class UHephaestusBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("HephaestusBPLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HephaestusBPLibrary")
	}
	static class UHephaestusBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHephaestusBPLibrary>();
	}
};
DUMPER7_ASSERTS_UHephaestusBPLibrary;

}

