#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HGS_Weapon_Base

#include "Basic.hpp"

#include "HGS_Weapon_Base_classes.hpp"
#include "HGS_Weapon_Base_parameters.hpp"


namespace SDK
{

// Function HGS_Weapon_Base.HGS_Weapon_Base_C.ExecuteUbergraph_HGS_Weapon_Base
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHGS_Weapon_Base_C::ExecuteUbergraph_HGS_Weapon_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HGS_Weapon_Base_C", "ExecuteUbergraph_HGS_Weapon_Base");

	Params::HGS_Weapon_Base_C_ExecuteUbergraph_HGS_Weapon_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HGS_Weapon_Base.HGS_Weapon_Base_C.DisData__UpdateFunc
// (BlueprintEvent)

void AHGS_Weapon_Base_C::DisData__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HGS_Weapon_Base_C", "DisData__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HGS_Weapon_Base.HGS_Weapon_Base_C.DisData__FinishedFunc
// (BlueprintEvent)

void AHGS_Weapon_Base_C::DisData__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HGS_Weapon_Base_C", "DisData__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

