#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: hys_yinbingniumo_01_Weapon

#include "Basic.hpp"

#include "hys_yinbingniumo_01_Weapon_classes.hpp"
#include "hys_yinbingniumo_01_Weapon_parameters.hpp"


namespace SDK
{

// Function hys_yinbingniumo_01_Weapon.hys_yinbingniumo_01_Weapon_C.ExecuteUbergraph_hys_yinbingniumo_01_Weapon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ahys_yinbingniumo_01_Weapon_C::ExecuteUbergraph_hys_yinbingniumo_01_Weapon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hys_yinbingniumo_01_Weapon_C", "ExecuteUbergraph_hys_yinbingniumo_01_Weapon");

	Params::hys_yinbingniumo_01_Weapon_C_ExecuteUbergraph_hys_yinbingniumo_01_Weapon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

