#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HYS_XiZhangLao_01_Weapon

#include "Basic.hpp"


namespace SDK::Params
{

// Function HYS_XiZhangLao_01_Weapon.HYS_XiZhangLao_01_Weapon_C.ExecuteUbergraph_HYS_XiZhangLao_01_Weapon
// 0x0004 (0x0004 - 0x0000)
struct HYS_XiZhangLao_01_Weapon_C_ExecuteUbergraph_HYS_XiZhangLao_01_Weapon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_HYS_XiZhangLao_01_Weapon_C_ExecuteUbergraph_HYS_XiZhangLao_01_Weapon;

}

