#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PDS_lingzhijing_01a_weapon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HGS_Weapon_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PDS_lingzhijing_01a_weapon.PDS_lingzhijing_01a_weapon_C
// 0x0008 (0x0348 - 0x0340)
class APDS_lingzhijing_01a_weapon_C final : public AHGS_Weapon_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PDS_lingzhijing_01a_weapon_C;       // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_PDS_lingzhijing_01a_weapon(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PDS_lingzhijing_01a_weapon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PDS_lingzhijing_01a_weapon_C")
	}
	static class APDS_lingzhijing_01a_weapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APDS_lingzhijing_01a_weapon_C>();
	}
};
DUMPER7_ASSERTS_APDS_lingzhijing_01a_weapon_C;

}

