#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_luoshaqiaolian_pa

#include "Basic.hpp"

#include "SceneInactiveActor_HangStructureBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SM_luoshaqiaolian_pa.SM_luoshaqiaolian_pa_C
// 0x0000 (0x02A8 - 0x02A8)
class ASM_luoshaqiaolian_pa_C final : public ASceneInactiveActor_HangStructureBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SM_luoshaqiaolian_pa_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SM_luoshaqiaolian_pa_C")
	}
	static class ASM_luoshaqiaolian_pa_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASM_luoshaqiaolian_pa_C>();
	}
};
DUMPER7_ASSERTS_ASM_luoshaqiaolian_pa_C;

}

