#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TexAlphaDA

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class TexAlphaDA.TexAlphaDataAsset
// 0x0028 (0x0058 - 0x0030)
class UTexAlphaDataAsset final : public UDataAsset
{
public:
	int32                                         SizeX;                                             // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SizeY;                                             // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FColor>                         ColorData;                                         // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FLinearColor>                   FloatColorData;                                    // 0x0048(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TexAlphaDataAsset")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TexAlphaDataAsset")
	}
	static class UTexAlphaDataAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTexAlphaDataAsset>();
	}
};
DUMPER7_ASSERTS_UTexAlphaDataAsset;

}

